### ISSUE TITLE
NoSuchMethodError: MongoIdentifier

### ISSUE THREAD

**Issue by joeboyscout04** [foursquare/rogue#104]
I previously was using Lift 2.5.1, Rogue 2.2.0, and was trying to upgrade to Lift 2.6 RC1, Rogue 2.4.0. 

I'm getting the following error when trying to perform any queries using the upgraded packages:

java.lang.NoSuchMethodError: net.liftweb.mongodb.MongoMeta.mongoIdentifier()Lnet/liftweb/mongodb/MongoIdentifier;
	at com.foursquare.rogue.LiftDBCollectionFactory$.getInstanceName(LiftQueryExecutor.scala:27)
	at com.foursquare.rogue.MongoJavaDriverAdapter.runCommand(MongoJavaDriverAdapter.scala:27)
	at com.foursquare.rogue.MongoJavaDriverAdapter.doQuery(MongoJavaDriverAdapter.scala:274)
	at com.foursquare.rogue.MongoJavaDriverAdapter.query(MongoJavaDriverAdapter.scala:169)
	at com.foursquare.rogue.QueryExecutor$class.fetch(QueryExecutor.scala:65)
	at com.foursquare.rogue.LiftQueryExecutor.fetch(LiftQueryExecutor.scala:36)
	at com.foursquare.rogue.ExecutableQuery.fetch(ExecutableQuery.scala:57)
	at .<init>(<console>:12)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:760)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:805)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:717)
	at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:581)
	at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:588)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:591)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:882)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:904)
	at org.jetbrains.plugins.scala.compiler.rt.ConsoleRunner.main(ConsoleRunner.java:64)

There is a related post along with some of the workarounds here: https://groups.google.com/forum/#!msg/liftweb/QSsjKLjhR9g/PouK-phiuuQJ

but I was wondering if you were going to update the main trunk of Rogue to solve this issue anytime soon. Thanks,

**Comment by joeboyscout04** [comment]
Any thoughts about merging in this pull request and issuing a quick update? Is anyone maintaining this project still?

**Comment by jliszka** [comment]
So sorry for the delay, will merge it now!
